name: Deploy Javadoc

on:
  workflow_dispatch

jobs:
  publish:

    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Generate Javadoc
        run: nix develop --command bash -c "./gradlew aggregateJavadoc"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/docs/aggregateJavadoc
          branch: javadoc
